FREQ_BASE = 16985
FREQ_DIFF = 86

FREQ_0 = FREQ_BASE
FREQ_1 = FREQ_0 + FREQ_DIFF
FREQ_2 = FREQ_1 + FREQ_DIFF
FREQ_3 = FREQ_2 + FREQ_DIFF
FREQ_4 = FREQ_3 + FREQ_DIFF
FREQ_5 = FREQ_4 + FREQ_DIFF
FREQ_6 = FREQ_5 + FREQ_DIFF
FREQ_7 = FREQ_6 + FREQ_DIFF
FREQ_8 = FREQ_7 + FREQ_DIFF
FREQ_9 = FREQ_8 + FREQ_DIFF
FREQ_A = FREQ_9 + FREQ_DIFF
FREQ_B = FREQ_A + FREQ_DIFF
FREQ_C = FREQ_B + FREQ_DIFF
FREQ_D = FREQ_C + FREQ_DIFF
FREQ_E = FREQ_D + FREQ_DIFF
FREQ_F = FREQ_E + FREQ_DIFF
FREQ_START = FREQ_F + FREQ_DIFF
FREQ_STOP = FREQ_START + FREQ_DIFF
FREQ_SPECIAL = FREQ_STOP + FREQ_DIFF

START_BYTE = 170
STOP_BYTE = 13