FREQ_BASE = 1032
FREQ_DIFF = 43

FREQ_0 = FREQ_BASE
FREQ_1 = FREQ_0 + (FREQ_DIFF * 3)
FREQ_2 = FREQ_1 + (FREQ_DIFF * 3)
FREQ_3 = FREQ_2 + (FREQ_DIFF * 3)
FREQ_4 = FREQ_3 + (FREQ_DIFF * 3)
FREQ_5 = FREQ_4 + (FREQ_DIFF * 3)
FREQ_6 = FREQ_5 + (FREQ_DIFF * 3)
FREQ_7 = FREQ_6 + (FREQ_DIFF * 3)
FREQ_8 = FREQ_7 + (FREQ_DIFF * 3)
FREQ_9 = FREQ_8 + (FREQ_DIFF * 3)
FREQ_A = FREQ_9 + (FREQ_DIFF * 3)
FREQ_B = FREQ_A + (FREQ_DIFF * 3)
FREQ_C = FREQ_B + (FREQ_DIFF * 3)
FREQ_D = FREQ_C + (FREQ_DIFF * 3)
FREQ_E = FREQ_D + (FREQ_DIFF * 3)
FREQ_F = FREQ_E + (FREQ_DIFF * 3)
FREQ_DELIMITER = FREQ_F + (FREQ_DIFF * 3)

# Frequency = np.abs(np.fft.rfft(indata[:, 0], n = 1024))[index] * 43
FREQ_0_INDEX = 24	# 1032 Hz
FREQ_1_INDEX = 27
FREQ_2_INDEX = 30
FREQ_3_INDEX = 33
FREQ_4_INDEX = 36
FREQ_5_INDEX = 39
FREQ_6_INDEX = 42
FREQ_7_INDEX = 45
FREQ_8_INDEX = 48
FREQ_9_INDEX = 51
FREQ_A_INDEX = 54
FREQ_B_INDEX = 57
FREQ_C_INDEX = 60
FREQ_D_INDEX = 63
FREQ_E_INDEX = 66
FREQ_F_INDEX = 69
FREQ_DELIMITER_INDEX = 72


START_BYTE = 170
STOP_BYTE = 126